name: 'SWM GitHub Actions Basic'

on: push    # 트리거, 지금은 push 했을 때 아래 jobs가 실행되게 설정한 것, []에 여러 개 넣어서도 사용 가능

env:  # 위치에 따라 전역 변수, 지역 변수처럼 사용 가능
  GLOBAL_LEVEL: "This value comes from the WORKFLOW level"
  PRESET_VALUE: "This is the preset value"

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest    # 실행되는 os의 종류

    env:
      JOB_LEVEL_1: "This value comes from the WORKFLOW level"

    steps: 
    - name: Say Hello World 1     # - 표시가 배열이라는 뜻
      shell: bash

      env:
        STEP_LEVEL_1: "This value comes from the WORKFLOW level"

      run: |
        echo "Hello World from step 1"
        echo "Global level: ${{ env.GLOBAL_LEVEL}}"
        echo "Job level 1: ${{ env.JOB_LEVEL_1}}"
        echo "Job level 2: ${{ env.JOB_LEVEL_2}}"
        echo "Step level 1: ${{ env.STEP_LEVEL_1}}"
        echo "Step level 2: ${{ env.STEP_LEVEL_2}}"

    - name: Say Hello World 2
      shell: pwsh

      env:
        STEP_LEVEL2: "This value comes from the WORKFLOW level"

      # 각 스코프에 들어오는 변수만 참조 가능
      run: |
        echo "Hello World from step 2"
        echo "Global level: ${{ env.GLOBAL_LEVEL}}"
        echo "Job level 1: ${{ env.JOB_LEVEL_1}}"
        echo "Job level 2: ${{ env.JOB_LEVEL_2}}"
        echo "Step level 1: ${{ env.STEP_LEVEL_1}}"
        echo "Step level 2: ${{ env.STEP_LEVEL_2}}"

    - name: Set environment variable 1
      shell: bash
      run: |
        echo "STEPSET_VALUE_1='This is he value 1 set in the step'" >> $GITHUB_ENV

    # - 환경 변수 동적으로 세팅
    - name: Set environment variable 2
      shell: pwsh
      run: |
        echo "STEPSET_VALUE_2='This is he value 2 set in the step'" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

    # - 세팅한 환경 변수 가져와서 사용
    - name: Get environment variables in powershell
      shell: pwsh
      run: |
        echo "Value 1: $env:STEPSET_VALUE_1"
        echo "Value 2: $env:STEPSET_VALUE_2"

    - name: Get environment variables in bash
      shell: bash
      run: |
        echo "Value 1: $STEPSET_VALUE_1"
        echo "Value 2: $STEPSET_VALUE_2"

    - name: Set output value
      id: first
      shell: bash
      run: |
        first_value="This is the value for the first output" 

        echo "::add-mask::$first_value"
        echo "::set-output name=april05::$first_value"  
        echo "april06=$first_value" >> $GITHUB_OUTPUT

    - name: Get output value
      shell: bash
      run: |
        echo "The value of the first output is: ${{steps.first.outputs.april05}}" 
        echo "The value of the first output is: ${{steps.first.outputs.april06}}"








  second-job:
    name: 'Second Job'

    runs-on: ubuntu-latest    # 실행되는 os의 종류

    env:
      JOB_LEVEL_2: "This value comes from the WORKFLOW level"

    steps: 
    - name: Say Hello World 1     # - 표시가 배열이라는 뜻
      shell: bash

      env:
        STEP_LEVEL_1: "This value comes from the WORKFLOW level"

      run: |
        echo "Hello World from step 1"
        echo "Global level: ${{ env.GLOBAL_LEVEL}}"
        echo "Job level 1: ${{ env.JOB_LEVEL_1}}"
        echo "Job level 2: ${{ env.JOB_LEVEL_2}}"
        echo "Step level 1: ${{ env.STEP_LEVEL_1}}"
        echo "Step level 2: ${{ env.STEP_LEVEL_2}}"

    - name: Say Hello World 2
      shell: pwsh

      env:
        STEP_LEVEL2: "This value comes from the WORKFLOW level"

      run: |
        echo "Hello World from step 2"
        echo "Global level: ${{ env.GLOBAL_LEVEL}}"
        echo "Job level 1: ${{ env.JOB_LEVEL_1}}"
        echo "Job level 2: ${{ env.JOB_LEVEL_2}}"
        echo "Step level 1: ${{ env.STEP_LEVEL_1}}"
        echo "Step level 2: ${{ env.STEP_LEVEL_2}}"