name: 'SWM GitHub Actions Basic'

on: push

jobs:
  first-job:
    name: 'First Job'

    # strategy:
    #   matrix:
    #     os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]
    #     nodejs: ['16.x', '18.x']

    # matrix 내의 os 배열 요소들에 대해 한 번씩 실행
    # runs-on: ${{ matrix.os }}

    runs-on: ubuntu-latest
 
    steps:
    - name: Say Hello World 1
      shell: bash
      run: |
        echo "Hello World from first job"

    # with를 통해 각 os에 대해 nodejs 내의 각 요소들을 하나씩 실행, 총 6번의 실행 발생 
    # - name: Say Hello World on ${{ matrix.os }}
    #   shell: bash
    #   run: |
    #     echo "Hello World on ${{ matrix.os }}"
    #     echo "Hello World on ${{ matrix.os }} with ${{matrix.nodejs}}" 
    
    # # conditional하게 실행
    # - name: Say Hello World on ${{ matrix.os }}
    #   if: matrix.os == 'ubuntu-latest'
    #   shell: bash
    #   # with를 통해 각 os에 대해 nodejs 내의 각 요소들을 하나씩 실행, 총 6번의 실행 발생  
    #   run: |
    #     echo "Hello Ubuntu on ${{ matrix.os }} with ${{matrix.nodejs}}" 

  second-job:
    name: 'Second Job'

    # 반드시 이전에 성공적으로 실행되어야 하는 작업을 추가
    needs:
    - first-job

    runs-on: ubuntu-latest

    # with를 통해 각 os에 대해 nodejs 내의 각 요소들을 하나씩 실행, 총 6번의 실행 발생  
    steps:
    - name: Say Hello World 2
      shell: bash
      run: |
        echo "Hello World from second job"
  