name: 'SWM GitHub Actions Basic'

on: push

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Send message to Webex space
      uses: ./
      with:
        webexToken: ${{ secrets.WEBEX_TOKEN }}
        webexRoomId: ${{ secrets.WEBEX_ROOM_ID }}
        bodyText: "Message sent by GitHub Actions from ${{ github.repository }}"
        bodyMarkdown: "Message sent by **GitHub Actions** from `${{ github.repository }}`"