name: 'SWM GitHub Actions Basic'

on: push

jobs:
  first-job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
    - name: Send message to Webex space
      shell: bash
      run: |
        curl --location --request POST 'https://webexapis.com/v1/messages' \
        --header 'Authorization: Bearer ${{ secrets.WEBEX_TOKEN }}' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "roomId": "Y2lzY29zcGFyazovL3VybjpURUFNOnVzLXdlc3QtMl9yL1JPT00vMGYyN2NhZjAtZDNiOS0xMWVkLWFlZDQtY2I1ZmM2YTNmZmFj",
          "text": "Message sent by GitHub Actions from ${{ github.repository }}"
        }'
        echo "Y2lzY29zcGFyazovL3VybjpURUFNOnVzLXdlc3QtMl9yL1JPT00vMGYyN2NhZjAtZDNiOS0xMWVkLWFlZDQtY2I1ZmM2YTNmZmFj"

    - name: Post Message to Webex Room
      # 깃헙 레포를 불러온 것, @뒤에 브랜치 이름이나 버전을 쓰면 됨
      uses: chrivand/action-webex-js@main
      env:
        WEBEX_TOKEN: ${{ secrets.WEBEB_TOKEN }}
        WEBEX_ROOM_ID: ${{ secrets.WEBEX_ROOM_ID }}
        MARKDOWN_MESSAGE: "깃헙 액션 101 워크샵에서 보내는 메시지입니다. 저는 이태규입니다. custom action으로 보내는 메시지입니다. ${{ github.repository }}."